#!/bin/bash
cd `dirname "$0"`/..

set -e

xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -project Tugh.xcodeproj -scheme 'Tugh' clean build test
